name: bloc_helpers
description: Set of helpers class and function to implements Bloc pattern
homepage: https://github.com/lejard-h/bloc_helpers
author: Hadrien Lejard <hadrien.lejard@gmail.com>
version: 0.0.2

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  rxdart: '>=0.17.0 <1.0.0'
  meta: ^1.1.0